---
title: Fast Visualization of High-Dimensional Data via Parallelized UMAP on GPUs
subtitle: ---
author: Peter Eisenmann

lang: en
fontsize: 11pt
linestretch: 1
documentclass: scrreprt
top-level-division: chapter
toc: yes
toc-depth: 2
lof: yes
secnumdepth: 2

# crossref custumization
figPrefix: ["Fig.", "Figs."]
eqnPrefix: ["Eq.", "Eqns."]
tblPrefix: ["Tbl.", "Tbls."]
secPrefix: ["Section", "Sections"]
# TODO: chapter prefix
autoEqnLabels: false
cref: true
bibliography: makefiles/references.yaml
citation-style: makefiles/ieee-with-url-no-online.csl
reference-section-title: Bibliography
header-includes:
    \usepackage[ruled,vlined,linesnumbered]{algorithm2e}
    \usepackage{amssymb}
    # bad \usepackage[utf8x]{inputenc}
    #- \usepackage[onehalfspacing]{setspace}
    #- \usepackage{chemfig}
include-before: |
  I hereby declare that this document has been composed by myself and describes my own work, unless otherwise acknowledged in the text.
  Ich versichere wahrheitsgemäß, die Arbeit selbstständig verfasst, alle benutzten Hilfsmittel vollständig und genau angegeben und alles kenntlich gemacht zu haben, was aus Arbeiten anderer unverändert oder mit Abänderungen entnommen wurde sowie die Satzung des KIT zur Sicherung guter wissenschaftlicher Praxis in der jeweils gültigen Fassung beachtet zu haben.
  \vspace{2cm}
  \begin{flushright}
  \begin{tabular}{lr}
      \multicolumn{2}{c}{\rule[0.1cm]{8cm}{0.1pt}}\\
      & Karlsruhe, 29.04.2019\\
  \end{tabular}
  \end{flushright}
---
