---
title-meta: On the topology of Lipschitz maps
author: Fjodor Motovilov

titlepage: false

lang: en
fontsize: 11pt
linestretch: 1 # line spacing
documentclass: scrreprt
top-level-division: chapter
toc: true # table of contents
toc-depth: 2 #chapter depth to list in table of contents
lof: false # list of figures
lot: false # list of tables
secnumdepth: 2

# crossref custumization
figPrefix: ["Figure", "Figures"]
eqnPrefix: ["",""]
tblPrefix: ["Tbl.", "Tbls."]
secPrefix: ["Section", "Sections"]
# TODO: chapter prefix
autoEqnLabels: false
cref: true
bibliography: makefiles/references.yaml
# find citation styles at https://www.zotero.org/styles
citation-style: makefiles/ieee-with-url-no-online.csl
reference-section-title: Bibliography
header-includes:
    \usepackage[ruled,vlined,linesnumbered]{algorithm2e}
    \usepackage{amssymb}
    \usepackage{pdfpages}
    \usepackage{amsthm}
    \usepackage{derivative}
    \usepackage{tikz-cd}
    \newtheorem{lemma}{Lemma}[chapter]
    \newtheorem*{claim}{Claim}
    \theoremstyle{definition}
    \newtheorem*{definition}{Definition}
    \newtheorem{theorem}[lemma]{Theorem}
    \newtheorem{example}[lemma]{Example}
    \newtheorem{proposition}[lemma]{Proposition}
    \newtheorem{assumption}{Assumption}
    \theoremstyle{definition}
    \newtheorem*{observation}{Observation}
    \theoremstyle{definition}
    \newtheorem*{remark}{Remark}
    \newcommand\rhocap[1]{\mathop{\mbox{${#1}$-$\mathrm{cap}$}}}
    \newcommand\R{\mathbb{R}}
    \newcommand\dx{\mathrm{d}}
    \newcommand\Z{\mathbb{Z}}
    \newcommand\N{\mathbb{N}}
    \newcommand\lessthan{<}
subparagraph: yes
    #- \usepackage[onehalfspacing]{setspace}
    #- \usepackage{chemfig}
include-before: |
    \pagebreak
    \begin{titlepage}
        \includepdf[pages={1}]{cover/cover.pdf}
    \end{titlepage}
    
    I hereby declare that this document has been composed by myself and describes my own work, unless otherwise acknowledged in the text.
    \vspace{2cm}  
    Ich versichere wahrheitsgemäß, die Arbeit selbstständig verfasst, alle benutzten Hilfsmittel vollständig und genau angegeben und alles kenntlich gemacht zu haben, was aus Arbeiten anderer unverändert oder mit Abänderungen entnommen wurde sowie die Satzung des KIT zur Sicherung guter wissenschaftlicher Praxis in der jeweils gültigen Fassung beachtet zu haben.
    \vspace{2cm}
    \begin{flushright}
    \begin{tabular}{lr}
      \multicolumn{2}{c}{\rule[0.1cm]{8cm}{0.1pt}}\\
      & Karlsruhe, 18.08.2022\\
    \end{tabular}
    \end{flushright}
    
    \pagebreak
    
    \chapter*{Abstract}
    
    We discuss the 2017 expository paper on quantitative topology by Larry Guth. The paper provides a more accessible take on two 2016 papers by Chambers, Dotterer, Ferry, Manin and Weinberger, which jointly gave an almost complete answer to Gromov's question: Given a Lipschitz continuous null-homotopic map between spheres $f: S^m \rightarrow S^n$, with Lipschitz constant $L$, what is the best Lipschitz constant over Lipschitz null-homotopies of $f$?

    \begingroup
    \renewcommand{\cleardoublepage}{}
    \renewcommand{\clearpage}{}
    \chapter*{Zusammenfassung}
    \endgroup
    
    Wir besprechen eine Übersichtsarbeit im Bereich der quantitativen Topologie von Larry Guth aus dem Jahr 2017. Seine Arbeit ermöglicht einen einfacheren Zugang zu zwei weiteren Arbeiten aus dem Jahr 2016, in denen es die Autoren Chambers, Dotterer, Ferry, Manin und Weinberger schaffen, eine fast vollständige Antwort auf die folgende Frage von Gromov zu geben: Gegeben sei eine nullhomotope Abbildung $f: S^m \rightarrow S^n$, Lipschitzstetig mit der Lipschitzkonstante $L$. Was ist die bestmögliche Lipschitzkonstante von allen Lipschitz-Nullhomotopien von $f$?
---
