---
title-meta: Unnamed Thesis Project
author: Fjodor Motovilov

titlepage: false

lang: en
fontsize: 11pt
linestretch: 1 # line spacing
documentclass: scrreprt
top-level-division: chapter
toc: true # table of contents
toc-depth: 2 #chapter depth to list in table of contents
lof: false # list of figures
lot: false # list of tables
secnumdepth: 2

# crossref custumization
figPrefix: ["Figure", "Figures"]
eqnPrefix: ["",""]
tblPrefix: ["Tbl.", "Tbls."]
secPrefix: ["Section", "Sections"]
# TODO: chapter prefix
autoEqnLabels: false
cref: true
bibliography: makefiles/references.yaml
# find citation styles at https://www.zotero.org/styles
citation-style: makefiles/ieee-with-url-no-online.csl
reference-section-title: Bibliography
header-includes:
    \usepackage[ruled,vlined,linesnumbered]{algorithm2e}
    \usepackage{amssymb}
    \usepackage{pdfpages}
    \usepackage{amsthm}
    \newtheorem{lemma}{Lemma}[chapter]
    \newtheorem*{claim}{Claim}
    \theoremstyle{definition}
    \newtheorem*{definition}{Definition}
    \newtheorem{theorem}[lemma]{Theorem}
    \newtheorem{example}[lemma]{Example}
    \newtheorem{assumption}{Assumption}
    \theoremstyle{definition}
    \newtheorem*{observation}{Observation}
    \theoremstyle{definition}
    \newtheorem*{remark}{Remark}
    \newcommand\rhocap[1]{\mathop{\mbox{${#1}$-$\mathrm{cap}$}}}
subparagraph: yes
    #- \usepackage[onehalfspacing]{setspace}
    #- \usepackage{chemfig}
include-before: |
    \pagebreak
    \begin{titlepage}
        \includepdf[pages={1}]{cover/cover.pdf}
    \end{titlepage}
    
    I hereby declare that this document has been composed by myself and describes my own work, unless otherwise acknowledged in the text.
    \vspace{2cm}  
    Ich versichere wahrheitsgemäß, die Arbeit selbstständig verfasst, alle benutzten Hilfsmittel vollständig und genau angegeben und alles kenntlich gemacht zu haben, was aus Arbeiten anderer unverändert oder mit Abänderungen entnommen wurde sowie die Satzung des KIT zur Sicherung guter wissenschaftlicher Praxis in der jeweils gültigen Fassung beachtet zu haben.
    \vspace{2cm}
    \begin{flushright}
    \begin{tabular}{lr}
      \multicolumn{2}{c}{\rule[0.1cm]{8cm}{0.1pt}}\\
      & Karlsruhe, 10.05.2022\\
    \end{tabular}
    \end{flushright}
    
    \pagebreak
    
    \chapter*{Abstract}
    
    Some English abstract.

    \begingroup
    \renewcommand{\cleardoublepage}{}
    \renewcommand{\clearpage}{}
    \chapter*{Zusammenfassung}
    \endgroup
    
    Eine deutsche Zusammenfassung.
---
