---
title-meta: Fast Visualization of High-Dimensional Data via Parallelized UMAP on GPUs
author: Peter Eisenmann

titlepage: false

lang: en
fontsize: 11pt
linestretch: 1 # line spacing
documentclass: scrreprt
top-level-division: chapter
toc: yes # table of contents
toc-depth: 2 #chapter depth to list in table of contents
lof: yes # list of figures
lot: yes # list of figures
secnumdepth: 2

# crossref custumization
figPrefix: ["Figure", "Figures"]
eqnPrefix: ["Eq.", "Eqns."]
tblPrefix: ["Tbl.", "Tbls."]
secPrefix: ["Section", "Sections"]
# TODO: chapter prefix
autoEqnLabels: false
cref: true
bibliography: makefiles/references.yaml
# find citation styles at https://www.zotero.org/styles
citation-style: makefiles/ieee-with-url-no-online.csl
reference-section-title: Bibliography
header-includes:
    \usepackage[ruled,vlined,linesnumbered]{algorithm2e}
    \usepackage{amssymb}
    \usepackage{pdfpages}
subparagraph: yes
    #- \usepackage[onehalfspacing]{setspace}
    #- \usepackage{chemfig}
include-before: |
    \pagebreak
    \begin{titlepage}
        \includepdf[pages={1}]{cover/cover.pdf}
    \end{titlepage}
    
    I hereby declare that this document has been composed by myself and describes my own work, unless otherwise acknowledged in the text.
    \vspace{2cm}  
    Ich versichere wahrheitsgemäß, die Arbeit selbstständig verfasst, alle benutzten Hilfsmittel vollständig und genau angegeben und alles kenntlich gemacht zu haben, was aus Arbeiten anderer unverändert oder mit Abänderungen entnommen wurde sowie die Satzung des KIT zur Sicherung guter wissenschaftlicher Praxis in der jeweils gültigen Fassung beachtet zu haben.
    \vspace{2cm}
    \begin{flushright}
    \begin{tabular}{lr}
      \multicolumn{2}{c}{\rule[0.1cm]{8cm}{0.1pt}}\\
      & Karlsruhe, 30.05.2019\\
    \end{tabular}
    \end{flushright}
    
    \pagebreak
    
    \chapter*{Abstract}
    
    Visualization is important for humans to perceive, analyze and understand data.
    Exploratory Data Analysis is essential in fields such as neural networks, deep-learning and data science in general.
    Unfortunately data in these fields commonly has hundreds or thousands of dimensions, making classic visualization techniques unsuitable.
    In recent years the dimensionality reduction algorithm t-SNE gained popularity.
    It preserves local structures, allowing for meaningful visualizations of complex data.
    UMAP is a new algorithm, that challenges t-SNE as the status quo
    It provides better performance in both, execution time and quality of graphical results.
    This thesis explores the functionality of UMAP and tries to improve its performance further, by parallelizing it to execute on graphics cards, GPUs.
    Profiling the GPU version, GPUMAP, shows speedups of up to sixty times on current hardware.

    \begingroup
    \renewcommand{\cleardoublepage}{}
    \renewcommand{\clearpage}{}
    \chapter*{Zusammenfassung}
    \endgroup
    
    Visualisierungen sind wichtig für Menschen um Daten zu betrachten, zu analysieren und zu verstehen.
    Explorative Datenanalyse ist essentiell in Bereichen wie Deep-Learning, Neuronale Netze und Data Science allgemein.
    Allerdings haben Daten in diesen Bereichen oft hunderte oder tausende von Dimensionen, was es klassischen Visualisierungstechniken unmöglich macht, sie darzustellen.
    In den letzten Jahren gewann t-SNE als eine Methode zur Dimensionsreduktion an Beliebtheit.
    t-SNE erhält lokale Strukturen, was eine aussagekräftige Visualisierung von komplexen Daten ermöglicht.
    UMAP ist ein aktuell veröffentlichter Algorithmus, der t-SNE als den Status Quo infrage stellt.
    Er bietet bessere grafische Ergebnisse bei zugleich schnellerer Ausführung.
    Diese Arbeit untersucht die Funktionalität von UMAP und versucht durch eine Parallelisierung des Algorithmuses auf Grafikkarten (GPUs), dessen Leistung noch weiter zu verbessern.
    Messungen der GPU-Version GPUMAP zeigen bis zu sechzigfache Beschleuningungen auf aktueller Hardware.
---
