---
title: Fast Visualization of High-Dimensional Data via Parallelized UMAP on GPUs
subtitle: ---
author: Peter Eisenmann

lang: en
fontsize: 11pt
linestretch: 1
documentclass: scrreprt
top-level-division: chapter
toc: yes
toc-depth: 2
lof: yes
secnumdepth: 2
# crossref custumization
figPrefix: ["Fig.", "Figs."]
eqnPrefix: ["Eq.", "Eqns."]
tblPrefix: ["Tbl.", "Tbls."]
secPrefix: ["Section", "Sections"]
# TODO: chapter prefix
autoEqnLabels: false
cref: true
bibliography: makefiles/references.yaml
citation-style: makefiles/ieee-with-url.csl
reference-section-title: Bibliography
header-includes:
    \usepackage[ruled,vlined,linesnumbered]{algorithm2e}
    \usepackage{amssymb}
    # bad \usepackage[utf8x]{inputenc}
    #- \usepackage[onehalfspacing]{setspace}
    #- \usepackage{chemfig}
include-before: |
  I hereby declare that this document has been composed by myself and describes my own work, unless otherwise acknowledged in the text.
  \vspace{2cm}
  \begin{flushright}
  \begin{tabular}{lr}
      \multicolumn{2}{c}{\rule[0.1cm]{8cm}{0.1pt}}\\
      & Karlsruhe, dd.mm.yyyy\\
  \end{tabular}
  \end{flushright}
  All websites in this work were last accessed on the 20.03.2019.
---
